@ECHO OFF

ECHO Upgrading pip .........
	python -m pip install --upgrade pip
Echo Installing setuptools .........
	pip install --upgrade pip setuptools wheel
Echo Building Package .........
	python -m pip install -e .
Echo Installing pre-commit .........
	pre-commit install
